[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Correct redirect rules - API routes to functions
[[redirects]]
  from = "/api/crypto-listings"
  to = "/.netlify/functions/crypto-listings"
  status = 200
  force = true

[[redirects]]
  from = "/api/perplexity-score"
  to = "/.netlify/functions/perplexity-score"
  status = 200
  force = true

# General API fallback
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200