[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Debug redirect for testing
[[redirects]]
  from = "/debug-api/*"  
  to = "/.netlify/functions/:splat"
  status = 200