[build]
  publish = "."
  functions = "netlify/functions"
  command = "node netlify-build.js"
  # Inject environment variables at build time
  environment = { SECRETS_SCAN_OMIT_PATHS = "js/firebase-config-real.js" }

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/js/firebase-config-demo.js"
  to = "/js/firebase-config-real.js"
  status = 301

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200