[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  included_files = ["netlify/functions/**"]

# Explicit redirects matching function names exactly
[[redirects]]
  from = "/api/crypto-listings"
  to = "/.netlify/functions/crypto-listings"
  status = 200
  force = true

[[redirects]]
  from = "/api/perplexity-score"
  to = "/.netlify/functions/perplexity-score"
  status = 200
  force = true

# Fallback for any other API calls
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Debug routes for testing
[[redirects]]
  from = "/.netlify/functions/crypto-listings"
  to = "/.netlify/functions/crypto-listings"
  status = 200

[[redirects]]
  from = "/.netlify/functions/perplexity-score"
  to = "/.netlify/functions/perplexity-score"
  status = 200