[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'Functions ready - deploying crypto-listings and perplexity-score'"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["node-fetch"]

# Primary API routes
[[redirects]]
  from = "/api/crypto-listings"
  to = "/.netlify/functions/crypto-listings"
  status = 200
  force = true

[[redirects]]
  from = "/api/perplexity-score"
  to = "/.netlify/functions/perplexity-score"
  status = 200
  force = true

# Debug routes for testing
[[redirects]]
  from = "/debug/crypto-listings"
  to = "/.netlify/functions/crypto-listings"
  status = 200

[[redirects]]
  from = "/debug/perplexity-score"
  to = "/.netlify/functions/perplexity-score"
  status = 200

# General API fallback
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Headers for function responses
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"